name: Weekly Report

on:
  push:
    branches: [ main ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/activity-report@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          publish_issues: true
          publish_top_liked_issues: 3
          publish_top_hot_issues: 3
          publish_pull_requests: true
          publish_contributors: true
          publish_commits: true
