name: Retrieve GitHub Info

on:
  push:
    branches: [ main ]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  retrieve_info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Retrieve commits
        run: |
          # Write a script to retrieve commits using GitHub API
          # Store the output in a file
        # Example:
        # curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/{owner}/{repo}/commits > commits.json

      - name: Retrieve pull requests
        run: |
          # Write a script to retrieve pull requests using GitHub API
          # Store the output in a file
        # Example:
        # curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/{owner}/{repo}/pulls > pull_requests.json

      - name: Retrieve contributors
        run: |
          # Write a script to retrieve contributors using GitHub API
          # Store the output in a file
        # Example:
        # curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/{owner}/{repo}/contributors > contributors.json
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: github-info
          path: |
            commits.json
            pull_requests.json
            contributors.json
      

# Add any other configurations, such as specifying branches or limiting the schedule.
