name: Retrieve GitHub Info

on:
  push:
    branches: [ main ]

jobs:
  retrieve-info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Retrieve commits
        id: commits
        run: |
          # Retrieve commits using GitHub API
          # Example command: curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/commits?since=$(date -d "last month" +%Y-%m-%dT00:00:00Z)"

      - name: Retrieve pull requests
        id: pull-requests
        run: |
          # Retrieve pull requests using GitHub API
          # Example command: curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/pulls?state=all&since=$(date -d "last month" +%Y-%m-%dT00:00:00Z)"

      - name: Retrieve contributors
        id: contributors
        run: |
          # Retrieve contributors using GitHub API
          # Example command: curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/stats/contributors"

...
      - name: Save commits as artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: commits
          path: commits.json # Path to the file containing commits data

      - name: Save pull requests as artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: pull-requests
          path: pull_requests.json # Path to the file containing pull requests data

      - name: Save contributors as artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: contributors
          path: contributors.json # Path to the file containing contributors data
...
