name: Weekly Report

on:
  push:
    branches: [ main ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Activity Report
        uses: wow-actions/activity-report@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          publish_issues: true
          publish_top_liked_issues: 3
          publish_top_hot_issues: 3
          publish_pull_requests: true
          publish_contributors: true
          publish_commits: true

      - name: Generate Activity Report
        uses: wow-actions/activity-report@v1.1.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Configuraciones adicionales
          time_zone: "UTC"
          report_days: 7
          output_file: "activity-report.md"

#      - name: Save Report to File
#        run: echo "${{ steps.activity-report.outputs.report }}" > activity_report.txt#
 #     - name: Upload Report as Artifact
 #       uses: actions/upload-artifact@v2
 #       with:
 #         name: activity-report
 #         path: activity_report.txt
