name: Retrieve GitHub Info

on:
  push:
    branches: [ main ]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  retrieve_info:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Retrieve commits
        run: |
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/commits?since=$(date -d '1 month ago' +%Y-%m-%dT00:00:00Z)" > commits.json

      - name: Retrieve pull requests
        run: |
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/pulls?state=all&since=$(date -d '1 month ago' +%Y-%m-%dT00:00:00Z)" > pull_requests.json

      - name: Retrieve contributors
        run: |
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/stats/contributors" > contributors.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: github-info
          path: |
            commits.json
            pull_requests.json
            contributors.json
