name: Weekly Report

on:
  push:
    branches: [ main ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Activity Report
        id: activity-report
        uses: wow-actions/activity-report@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          publish_issues: true
          publish_top_liked_issues: 3
          publish_top_hot_issues: 3
          publish_pull_requests: true
          publish_contributors: true
          publish_stargazers: true
          publish_commits: true
          publish_releases: true
        # Add other necessary parameters here

      - name: Generate Report File
        run: |
          echo "${{ steps.activity-report.outputs.template_issues_summary }}" > activity_report.txt
          echo "${{ steps.activity-report.outputs.template_pull_requests_summary }}" >> activity_report.txt
          # Add more lines to append other report sections as needed

      - name: Debug Output Variables
        run: |
          echo "Issues Summary: ${{ steps.activity-report.outputs.template_issues_summary }}"
          echo "Pull Requests Summary: ${{ steps.activity-report.outputs.template_pull_requests_summary }}"
          # Add more debug lines for other output variables

      - name: Upload Report as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: activity-report
          path: activity_report.txt
